### ISSUE TITLE
Colours being lost

### ISSUE THREAD

**Issue by davidwatkins73** [Ape/cogmindmod#1]
Just tried the mod - love the concept.  However the colours seem to be lost when it's active.

![image](https://user-images.githubusercontent.com/576829/54716331-658fd200-4b4d-11e9-9cdd-6602c508c30a.png)

![image](https://user-images.githubusercontent.com/576829/54716356-704a6700-4b4d-11e9-8342-ca5a4c49d235.png)

Versions
- Cogmind:  `Beta 8`
- Windows: 10 pro / 17134.648

I've tried a couple of fonts at different sizes, they all seem to have the same issue.
 
Probably unrelated, but the first time I ran Cogmind after installing the mod the app hung.  After killing it and restarting it seems fine.

**Comment by Ape** [comment]
Set `ratingBasedItemSpriteColors=0` in your `advanced.cfg`.
